### ISSUE TITLE
fatal: not a git repository (or any parent up to mount point /github)

### ISSUE THREAD

**Issue by scott-doyland-burrows** [terraform-docs/gh-actions#102]
Please see the screenshot:
![image](https://user-images.githubusercontent.com/61512176/217255332-c1497fbc-723d-4a23-bc78-9aca680fb943.png)

I run a workflow, that calls a reusable workflow, that in turn calls a composite action, and in turn that composite calls the tf docs action.  The tf docs action eventually gets run like this:

```
- name: Terraform docs
   if: github.event_name == 'pull_request'
   uses: terraform-docs/gh-actions@v1.0.0
   with:
     working-dir: ./terraform/terraform
     output-method: replace
```

My repo is checked out to a ```terraform``` directory, and in that I have a directory named ```terraform``` where the tf code is, like this:

```
- name: Checkout Code on PR
  if: |
  inputs.CodeCheckout == 'true' &&
  github.event_name == 'pull_request'
  uses: actions/checkout@v3
  with:
    path: terraform
    ref: ${{ github.event.pull_request.head.ref }}
```

I know the checkout is working OK as I can run terraform itself.

This is running on a ```ubuntu-latest``` github hosted runner.

I did some testing and can see the README.md is updated (ran a ```cat``` of the file from the github hosted runner after the failed tf docs action).

I have tried various settings for the tf docs action, such as ```find-dir```, altering the ```working-dir``` (such as removing the ```./``` from the directory name),  but it always fails with the same issue.
