### ISSUE TITLE
output-format overriding config file

### ISSUE THREAD

**Issue by Joey40** [terraform-docs/gh-actions#104]
### Describe the bug

Specifying a value for `output-format` or even not specifying it and using the default `markdown table` overrides the `formatter` specified in the config file.

### How can we reproduce it?

Create a config file with a formatter other than `markdown table`.  Then run the following Action:

``` YAML
    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: ./terraform
        config-file: ".terraform-docs.yml"
        git-push: "true"
```

The output will default to `markdown table` regardless of what is specified in the config file

### Environment information

Github Actions with Ubuntu-Latest image
