### ISSUE TITLE
Following guides I get the message: "Error: accepts 1 arg(s), received 4"

### ISSUE THREAD

**Issue by Bozz95** [terraform-docs/gh-actions#128]
### Describe the bug

I'm trying to run this action on a Gitea repository, whose actions should wokr the same as Github (more or less).

This is the code of the steps which are failing:

```yaml

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@v1
      with:
        config-file: "./.terraform-docs.yaml"
        working-dir: .
        output-file: ""
        output-method: ""
        args: ""

```

This is the content of my `terraform-docs.yaml`:

```yaml

formatter: "markdown table"

header-from: main.tf
footer-from: ""

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

```

When I push come commits the actions gives me this logs at the terraform-docs step:

```txt
::debug working_dir=.
::debug config_file=./.terraform-docs.yaml
::debug terraform-docs markdown table ${{ inputs.args }} --config ./.terraform-docs.yaml --output-template ${{ inputs.template }} .
Error: accepts 1 arg(s), received [4](https://git.lantechlongwave.it/Frametech/mde_setup_repo_account/actions/runs/24#jobstep-2-4)
```

The action is listening to pull requests.

I can't get it working.

Am I doing something wrong?

### Environment information

Action version: terraform-docs/gh-actions@v1

**Comment by seniordevops7** [comment]
Same problem here

**Comment by volker-raschek** [comment]
I took a look at the source code. While skimming through it, I noticed the following. The GitHub Action interprets `${{ inputs }}` as arguments. 

They are [passed](https://github.com/terraform-docs/gh-actions/blob/main/action.yml#L103) to the container image via environment variables, but are not substituted. 

```yaml
runs:
  using: docker
  image: "docker://quay.io/terraform-docs/gh-actions:1.4.1"
  env:
    INPUT_WORKING_DIR: ${{ inputs.working-dir }}
    INPUT_ATLANTIS_FILE: ${{ inputs.atlantis-file }}
    INPUT_FIND_DIR: ${{ inputs.find-dir }}
    INPUT_RECURSIVE: ${{ inputs.recursive }}
    INPUT_RECURSIVE_PATH: ${{ inputs.recursive-path }}
    INPUT_OUTPUT_FORMAT: ${{ inputs.output-format }}
    INPUT_OUTPUT_METHOD: ${{ inputs.output-method }}
    INPUT_OUTPUT_FILE: ${{ inputs.output-file }}
    INPUT_TEMPLATE: ${{ inputs.template }}
    INPUT_ARGS: ${{ inputs.args }}
    INPUT_INDENTION: ${{ inputs.indention }}
    INPUT_GIT_PUSH: ${{ inputs.git-push }}
    INPUT_GIT_COMMIT_MESSAGE: ${{ inputs.git-commit-message }}
    INPUT_CONFIG_FILE: ${{ inputs.config-file }}
    INPUT_FAIL_ON_DIFF: ${{ inputs.fail-on-diff }}
    INPUT_GIT_PUSH_SIGN_OFF: ${{ inputs.git-push-sign-off }}
    INPUT_GIT_PUSH_USER_NAME: ${{ inputs.git-push-user-name }}
    INPUT_GIT_PUSH_USER_EMAIL: ${{ inputs.git-push-user-email }}
    INPUT_GIT_SUB_DIR: ${{ inputs.git-sub-dir }}
```

As a result, `${{ inputs.args }}` and `${{ inputs.template }}` are interpreted as separate arguments. However, the terraform-docs program only expects one argument. This then leads to an error message stating that too many arguments have been passed: `Error: accepts 1 arg(s), received 4`.

If I fork this repository and define the `INPUT_` vars with empty values, the action runs successfully.
