### ISSUE TITLE
Action stopped working: Docker pull failed

### ISSUE THREAD

**Issue by bisskar** [terraform-docs/gh-actions#132]
### Describe the bug

![1](https://github.com/terraform-docs/gh-actions/assets/65374155/7c3238b9-3d69-4460-b552-43223277152f)

### How can we reproduce it?

Looks like after recent update action stopped working. 
```
docs:
        runs-on: ubuntu-latest
        needs: validate-fmt-plan
        steps:
        - uses: actions/checkout@v4
          with:
            ref: ${{ github.event.pull_request.head.ref }}
    
        - name: Render terraform docs and push changes back to PR
          uses: terraform-docs/gh-actions@main
          with:
            working-dir: .
            output-file: README.md
            output-method: inject
            git-push: "true"
```
### Environment information

Github workflow.
