### ISSUE TITLE
Configuration file completely ignored

### ISSUE THREAD

**Issue by tedivm** [terraform-docs/gh-actions#136]
### Describe the bug

When using this action I would expect the configuration file for the project to be used.

Instead this action passes in values via the command line flags, which overwrite the configuration file values.

### How can we reproduce it?

Create a configuration file, use the action, and watch it be ignored.

### Environment information

Github Actions with the latest version of the action.

**Comment by kieran-lowe** [comment]
noticed this as well, comparing the output from my run and it seems to be completely ignoring it.

**Comment by g--** [comment]
I found this in the debug output:

```
terraform-docs markdown table --config .terraform-docs.yml --output-mode inject --output-file README.md --output-template <!-- BEGIN_TF_DOCS -->
{{ .Content }}
<!-- END_TF_DOCS --> .
```

it looks like it is passing in the configuration file, but it's also specifying the default values of several other parameters.

I'm guessing one solution would be to not set the parameters unless GHA receives an explicit argument. This would have the effect of making terraform-docs' defaults this GHA's defaults.

**Comment by g--** [comment]
Here's a work-around: set the values with defaults explicitly to the empty string, like this:

```
    - name: Render terraform module docs
      uses: terraform-docs/gh-actions@main
      id: check
      with:
        working-dir: .
        config-file: .terraform-docs.yml

        # set values to blank so it uses the config file
        output-method:
        output-file:
        output-format:
        template: 
```
