### ISSUE TITLE
github.com host key verification failed when run locally using https://github.com/nektos/act

### ISSUE THREAD

**Issue by pkazi** [terraform-docs/gh-actions#146]
### Describe the bug

I am running this action locally using https://github.com/nektos/act.
It stucks for github.com host verification and - 
```
🐳  docker run image=quay.io/terraform-docs/gh-actions:1.3.0 platform= entrypoint=[] cmd=[] network="container:act-Terraform-and-JSON-Linter-Validate-Terraform-Modules-7ceb2ea698e15bd85f14b190163e3c5bddafab3929c2daaa329f51dbe58d0357"
The authenticity of host 'github.com (20.207.73.82)' can't be established.
| ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
| This key is not known by any other names.
```

### How can we reproduce it?

Run with act https://github.com/nektos/act
```
name: Generate terraform docs
on:
  - pull_request
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.3.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
```

### Environment information

terraform-docs/gh-actions@v1.3.0
OS - MacOS
