### ISSUE TITLE
Multi folder `working-dir` not properly split

### ISSUE THREAD

**Issue by fparga** [terraform-docs/gh-actions#36]
### Describe the bug

Using the action with multiple `working-dir` (like described in the [README](https://github.com/terraform-docs/gh-actions#multi-folder)) doesn't seem to properly split the string.

### How can we reproduce it?

Using this GitHub Workflow configuration:
```
name: Terraform Docs

on:
  - pull_request

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR branch
      uses: terraform-docs/gh-actions@v0.6.0
      with:
        working-dir: .,modules/ci-cd
        args: "--hide-all --show inputs --show outputs"
        output-file: README.md
        output-method: inject
        git-push: "true"
```

Fails with the following output:
```
::debug file=entrypoint.sh,line=66 working_dir=.modules/ci-cd
::debug file=entrypoint.sh,line=84 command=terraform-docs markdown table --indent 2 --hide-all --show inputs --show outputs .modules/ci-cd
Error: Error: Failed to read module directory: Module directory .modules/ci-cd does not exist or cannot be read.
```
