### ISSUE TITLE
Enable Verified Commits (with GPG key as secret)

### ISSUE THREAD

**Issue by dgteixeira** [terraform-docs/gh-actions#63]
### What problem are you facing?

I have Repositories that need to enforce Signed Commits, and would like to keep this action.

### How could terraform-docs help solve your problem?

**1st Hypothesis:**
- Integrate with the action the possibility to use GPG keys to verify the commits, when pushing.

**2nd Hypothesis:**
- Fix Issue #50, so that we can use other addons such as [crazy-max/ghaction-import-gpg@v2](https://github.com/crazy-max/ghaction-import-gpg) and [Add & Commit](https://github.com/marketplace/actions/add-commit) to improve our commits.

**Comment by pfilourenco** [comment]
Any update on this?

**Comment by apalmercari** [comment]
Any update on this?

**Comment by sunnyoswalcro** [comment]
Any update on this?

**Comment by SVendittelli** [comment]
While this did not solve my issue, it may help other people here: https://gist.github.com/swinton/03e84635b45c78353b1f71e41007fc7c

**Comment by exaucae** [comment]
how far are we from solving this with https://github.com/terraform-docs/gh-actions/pull/110 ?

**Comment by dgteixeira** [comment]
@exaucae, I believe that that PR might solve this issue, yes :)

One extra idea, might be to use the GraphQL API that uses GitHub's GPG key to verify the commits, through this GHA - https://github.com/planetscale/ghcommit-action

I saw this idea here: https://github.com/actions/runner/issues/667#issuecomment-1743258528

**Comment by etiennetremel** [comment]
Based on @dgteixeira suggestion and for anyone looking for a quick solution until #110 get merged, the following push verified commits:

```yaml
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: terraform-docs/gh-actions@main
      with:
        working-dir: .
        recursive: true
        recursive-path: modules
        output-file: README.md
        output-method: inject
    - uses: planetscale/ghcommit-action@v0.1.6
      with:
        commit_message: "terraform-docs: automated action"
        repo: ${{ github.repository }}
        branch: ${{ github.head_ref || github.ref_name }}
        file_pattern: 'modules/**/*.md'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
