### ISSUE TITLE
num_changed output is not set when pushing

### ISSUE THREAD

**Issue by josh-barker** [terraform-docs/gh-actions#64]
### Describe the bug

When `git-push` is set to `true`, the output `num_changed` has no value.

See https://github.com/terraform-docs/gh-actions/blob/main/src/docker-entrypoint.sh#L191

### How can we reproduce it?

```yaml
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update documentation in README.md
        id: doc_update
        if: github.ref != 'refs/heads/main'
        uses: terraform-docs/gh-actions@v0.10.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-commit-message: "docs: docs automatically updated by terraform-docs"
          git-push: "true"

      - name: Docs updated
        run: |
          echo ${{ toJSON(steps) }}
          exit 1
```

Docs Updated shows:

```bash
{
    "7d40844ea24e4dbe999f72fb0670e5d0": {
      "outputs": {},
      "outcome": "success",
      "conclusion": "success"
    },
    "doc_update": {
      "outputs": {},
      "outcome": "success",
      "conclusion": "success"
    }
  }
```

### Environment information

`terraform-docs/gh-actions@v0.10.0`
