### ISSUE TITLE
Template string has extra -'s

### ISSUE THREAD

**Issue by basilnsage** [terraform-docs/gh-actions#67]
### Describe the bug

If I run `terraform-docs` from the CLI, it generates an output file whose headers, footers read `<!-- BEGIN_TF_DOCS -->` and `<!-- END_TF_DOCS -->` respectively. However, the GitHub action expects headers, footers `<!--- BEGIN_TF_DOCS --->` and `<!--- END_TF_DOCS --->` respectively. Note the extra `-` characters. This causes the `sed` command (https://github.com/terraform-docs/gh-actions/blob/main/src/docker-entrypoint.sh#L150) to fail to match previously CLI-generated docs and so the github action never actually updates anything.

In short, this means that docs have to either all be generated from the CLI or generated from the github action. I cannot generate docs initially and then expect the action to take care of things moving forward, which is what I would expect.

### How can we reproduce it?

In a new or suitable test repo:
1. Populate files:
```
echo 'resoure "null_resource" "this" {}' > main.tf

mkdir -p .github/workflows
cat <<- "EOF" > .github/workflows/main.yml
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"

    - name: Check outputs
      run: |
        git status --porcelain
        cat README.md
EOF
```
1. Generate a README.md
```
terraform-docs markdown table . --output-file=README.md
```
1. Git add, commit, and push everything
1. On a new branch, update main.tf
```
echo 'resource "null_resource" "this2" {}' >> main.tf
```
1. Update README.md
```
terraform-docs markdown table . --output-file=README.md
```
1. Note the difference
```
git diff
```
1. Git add main.tf only. Commit and push
1. Open a PR
1. Check the results. The last step should print the contents of README.md, which have not been modified.

### Environment information

- terraform-docs version (use `terraform-docs --version`): terraform-docs version v0.15.0 darwin/amd64
- Go version (if you manually built. use `go version`): installed with Brew
- OS (e.g. Windows, MacOS): MacOS
