### ISSUE TITLE
Intended usage for mono repo. 

### ISSUE THREAD

**Issue by joeypiccola** [terraform-docs/gh-actions#70]
I have a single repo with a modules directory. Each directory in modules is a unique and standalone module. How would I configure the GH action to generate a `readme.md` in the root of each module directory? Thanks for the usage help. 

```
git_repos/az-modules/ 
➜ tree                 
.
├── .github
│   └── workflows
│       └── documentation.yml
├── README.md
└── modules
    ├── aks
    │   ├── main.tf
    │   ├── outputs.tf
    │   ├── variables.tf
    │   └── versions.tf
    ├── application_insights
    │   ├── main.tf
    │   ├── output.tf
    │   ├── variables.tf
    │   └── versions.tf
    ├── azuread_application
    │   ├── main.tf
    │   ├── output.tf
    │   ├── variables.tf
    │   └── versions.tf
```

**Comment by joeypiccola** [comment]
Using the following `.terraform-docs.yml` I can achieve what I want when manually calling `terraform-docs` outside of CI. Works great. 

```yml
# .terraform-docs.yml

formatter: "markdown"

output:
  file: "readme.md"
  mode: inject

recursive:
  enabled: true
  path: modules

header-from: main.tf

content: |-

  {{ .Header }}

  {{ .Inputs }}

  {{ .Outputs }}

sort:
  enabled: true
  by: required

settings:
  anchor: false
  html: false
  escape: false
  hide-empty: true
```

However, I can't seem to duplicate the recursion piece of it when run in CI. My current `documentation.yml` is below. As others have noted not all settings are pulled in via `config-file: .terraform-docs.yml`. 

```yml
name: Generate terraform docs
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        git-push: true
        working-dir: .
        config-file: .terraform-docs.yml
        output-method: inject
        output-file: readme.md
```
