### ISSUE TITLE
Unexpected input(s) 'recursive', 'recursive-path'

### ISSUE THREAD

**Issue by KB30497** [terraform-docs/gh-actions#77]
### Describe the bug
Adding '**recursive**' and '**recursive-path**' to the workflow file results in the following error:
`Warning: Unexpected input(s) 'recursive', 'recursive-path', valid inputs are ['entryPoint', 'args', 'config-file', 'working-dir', 'atlantis-file', 'find-dir', 'output-format', 'output-method', 'output-file', 'template', 'indention', 'git-push', 'git-push-user-name', 'git-push-user-email', 'git-commit-message', 'git-push-sign-off', 'fail-on-diff']`

Seems like they might not be included in v0.11.0 even though the examples make it seem like they are. Is that intended?

### How can we reproduce it?
```yaml
- name: Render Terraform Docs (Recursive)
  uses: terraform-docs/gh-actions@v0.11.0
  with:
    working-dir: .
    output-file: README.md
    output-method: inject
    recursive: true
    recursive-path: modules
```

### Environment information
Github Actions
